// src/components/MainPanel/MainPanel.tsx
import React, { forwardRef, useImperativeHandle } from 'react'
import { Tabs, Layout } from 'antd'
import { CloseOutlined } from '@ant-design/icons'
import { usePanelManagement } from '../../hooks/usePanelManagement'
import { PropertiesObject } from '../PropertiesPanel'

const { Content, Sider } = Layout

// 定义面板类型
export type PanelType = 'query' | 'function' | 'table' | 'view' | 'backup' | 'model' | 'bi' | 'object'

// 面板项接口
export interface PanelItem {
  id: string
  type: PanelType
  title: string
  content: React.ReactNode
}

// 定义组件引用类型
export interface MainPanelRef {
  createPanel: (type: PanelType, title: string, content: React.ReactNode) => void
  updatePanelContent: (panelId: string, content: React.ReactNode) => void
}

interface MainPanelProps {
  /**
   * 右侧属性面板内容
   */
  propertiesContent?: React.ReactNode
  /**
   * 当前选中的对象
   */
  selectedObject?: PropertiesObject | null
}

/**
 * 主操作区面板组件
 */
const MainPanel = forwardRef<MainPanelRef, MainPanelProps>(({
  propertiesContent,
  selectedObject: _selectedObject
}, ref) => {
  // 使用自定义hook管理面板状态
  const {
    panels,
    activePanelId,
    createPanel,
    updatePanelContent,
    handleClosePanel,
    handleSwitchPanel
  } = usePanelManagement()
  // 渲染标签页
  const renderTabs = () => {
    return panels.map(panel => ({
      key: panel.id,
      label: (
        <span>
          {panel.title}
          {/* 默认的"对象"面板不显示关闭按钮 */}
          {panel.id !== 'object-0' && (
            <CloseOutlined
              onClick={(e) => {
                e.stopPropagation()
                handleClosePanel(panel.id)
              }}
              style={{ marginLeft: '8px', cursor: 'pointer' }}
            />
          )}
        </span>
      ),
      children: panel.content
    }))
  }

  // 暴露方法给父组件
  useImperativeHandle(ref, () => ({
    createPanel,
    updatePanelContent
  }))

  return (
    <Layout style={{ height: '100%' }}>
      <Content style={{ padding: 0, overflow: 'auto', height: '100%' }}>
        <Tabs
          activeKey={activePanelId}
          items={renderTabs()}
          onChange={handleSwitchPanel}
          style={{ height: '100%' }}
          tabBarStyle={{ borderBottom: '1px solid #f0f0f0', paddingLeft: '16px' }}
        />
      </Content>
      <Sider
        width={280}
        style={{
          borderLeft: '1px solid #f0f0f0',
          background: '#fff',
          overflowY: 'auto'
        }}
        theme="light"
      >
        {propertiesContent || (
          <div style={{ padding: '16px' }}>
            <h3 style={{ marginBottom: '16px', fontSize: '14px', fontWeight: 'bold' }}>属性</h3>
            <p>选择一个对象查看其属性</p>
          </div>
        )}
      </Sider>
    </Layout>
  )
})

// 设置组件的displayName
MainPanel.displayName = 'MainPanel'

export default MainPanel

// src/components/MainPanel/index.vue
<template>
  <el-container class="main-panel">
    <el-main style="padding: 0; overflow: auto; height: 100%">
      <el-tabs
        v-model="activePanelId"
        @onTabChange="handleSwitchPanel"
        :style="{ height: '100%' }"
      >
        <el-tab-pane
          v-for="panel in panels"
          :key="panel.id"
          :name="panel.id"
        >
          <template #label>
            <span>
              {{ panel.title }}
              <el-icon
                v-if="panel.id !== 'object-0'"
                class="close-icon"
                @click.stop="handleClosePanel(panel.id)"
              >
                <Close />
              </el-icon>
            </span>
          </template>
          <component :is="panel.content" />
        </el-tab-pane>
      </el-tabs>
    </el-main>

    <el-aside
      width="280px"
      style="border-left: 1px solid #f0f0f0; background: #fff; overflow-y: auto"
    >
      <slot name="properties">
        <div v-if="propertiesContent" style="height: 100%; padding: 0;">
          <component :is="propertiesContent" />
        </div>
        <div v-else style="padding: 16px">
          <el-text tag="h3" style="margin-bottom: 16px; font-size: 14px; font-weight: bold">属性</el-text>
          <el-text type="info">选择一个对象查看其属性</el-text>
        </div>
      </slot>
    </el-aside>
  </el-container>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, nextTick } from 'vue'
import { Close } from '@element-plus/icons-vue'
import { usePanelManagement } from '../../composables/usePanelManagement'
import type { PropertiesObject } from '../PropertiesPanel'

export type PanelType = 'query' | 'function' | 'table' | 'view' | 'backup' | 'model' | 'bi' | 'object'

export interface PanelItem {
  id: string
  type: PanelType
  title: string
  content: any
}

export interface MainPanelRef {
  createPanel: (type: PanelType, title: string, content: any) => void
  updatePanelContent: (panelId: string, content: any) => void
}

interface MainPanelProps {
  propertiesContent?: any
  selectedObject?: PropertiesObject | null
}

const props = defineProps<MainPanelProps>()

const {
  panels,
  activePanelId,
  createPanel: _createPanel,
  updatePanelContent: _updatePanelContent,
  handleClosePanel: _handleClosePanel,
  handleSwitchPanel: _handleSwitchPanel
} = usePanelManagement()

const createPanel = (type: PanelType, title: string, content: any) => {
  _createPanel(type, title, content)
}

const updatePanelContent = (panelId: string, content: any) => {
  _updatePanelContent(panelId, content)
}

const handleClosePanel = (panelId: string) => {
  _handleClosePanel(panelId)
}

const handleSwitchPanel = (panelId: string) => {
  _handleSwitchPanel(panelId)
}

defineExpose({
  createPanel,
  updatePanelContent
})
</script>

<style scoped>
.main-panel {
  height: 100%;
}

.close-icon {
  margin-left: 8px;
  cursor: pointer;
}

.close-icon:hover {
  color: #f56c6c;
}
</style>
