// src/components/AppLayout/AppLayout.tsx
/**
 * 应用主布局组件
 */
import React from 'react'
import { Layout } from 'antd'
import HeaderBar from '../HeaderBar'
import ConnectionTree from '../ConnectionTree'
import MainPanel from '../MainPanel/MainPanel'
import ObjectPanel, { TableData } from '../ObjectPanel'
import FunctionPanel, { FunctionData } from '../FunctionPanel'
import PropertiesPanel from '../PropertiesPanel'
import { TreeNode, TreeNodeType } from '../../types/leftTree/tree'
import { useConnection } from '../../hooks/useConnection'
import { useDatabaseOperations } from '../../hooks/useDatabaseOperations'
import { useConnectionStore } from '../../store/connectionStore'
import { useSelection } from '../../hooks/useSelection'
import { formatBytes } from '../../utils/formatUtils'
import { ConnectionStatus, DatabaseStatus } from '../../types/leftTree/connection'
import { ObjectPanelType } from '../../types/headerBar/headerBar'

const { Sider, Content } = Layout


const mockFunctions: FunctionData[] = [
  { name: 'get_format', modifyDate: '2023-01-15', functionType: 'FUNCTION', deterministic: true, comment: 'Format a date or time value' },
  { name: 'uuid', modifyDate: '2023-01-15', functionType: 'FUNCTION', deterministic: false, comment: 'Generate a UUID value' },
  { name: 'version', modifyDate: '2023-01-15', functionType: 'FUNCTION', deterministic: false, comment: 'Return version of MySQL server' },
]

interface AppLayoutProps {
  /**
   * 活动连接ID
   */
  activeConnectionId?: string | null
  /**
   * 内容区域的子组件
   */
  children?: React.ReactNode
  /**
   * 处理新建连接按钮点击
   */
  onNewConnection?: () => void
  /**
   * 处理连接按钮点击
   */
  onConnect?: () => void
  /**
   * 处理新建查询按钮点击
   */
  onNewQuery?: () => void
  /**
   * 处理表按钮点击
   */
  onTable?: () => void
  /**
   * 处理视图按钮点击
   */
  onView?: () => void
  /**
   * 处理函数按钮点击
   */
  onFunction?: () => void
  /**
   * 处理用户按钮点击
   */
  onUser?: () => void
  /**
   * 处理其他按钮点击
   */
  onOther?: () => void
  /**
   * 处理查询按钮点击
   */
  onSearch?: () => void
  /**
   * 处理备份按钮点击
   */
  onBackup?: () => void
  /**
   * 处理自动运行按钮点击
   */
  onAutoRun?: () => void
  /**
   * 处理模型按钮点击
   */
  onModel?: () => void
  /**
   * 处理BI按钮点击
   */
  onBI?: () => void
}

/**
 * 应用主布局组件
 */
const AppLayout = ({
  activeConnectionId: propActiveConnectionId, // 使用下划线前缀表示未使用的参数
  onNewConnection,
  onConnect,
  onUser,
  onOther,
  onSearch,
  onAutoRun
}: AppLayoutProps) => {
  // 从hooks获取连接和数据库操作相关的状态和函数
  const { connectionStates, activeConnectionId: storeActiveConnectionId } = useConnection()
  const { databases, tables, databaseStates } = useConnectionStore()
  const { } = useDatabaseOperations()

  // 使用useSelection hook管理选中状态
  const {
    selectedTables,
    setSelectedTables,
    currentConnectionStatus,
    setCurrentConnectionStatus,
    selectedNode,
    setSelectedNode: updateSelectedNode,
    mainPanelRef,
    selectedObject
  } = useSelection()

  // 处理表打开事件，创建TableObject对象
  const handleTableOpen = (_record: TableData): void => {
    // 表打开事件由useSelection内部的useEffect自动处理selectedObject更新
  }

  // 创建ObjectPanel组件
  const createObjectPanelContent = (dataSource: TableData[] = [], nodeType?: TreeNodeType, nodeName?: string, databaseStatus?: DatabaseStatus) => {
    // 根据TreeNodeType映射到ObjectPanelType
    let objectPanelType: ObjectPanelType | undefined;
    if (nodeType === TreeNodeType.CONNECTION || nodeType === TreeNodeType.DATABASE || nodeType === TreeNodeType.TABLE) {
      objectPanelType = 'table';
    } else if (nodeType === TreeNodeType.VIEW) {
      objectPanelType = 'view';
    } else if (nodeType === TreeNodeType.FUNCTION) {
      objectPanelType = 'function';
    } else if (nodeType === TreeNodeType.USER) {
      objectPanelType = 'user';
    }

    return (
      <ObjectPanel
        dataSource={dataSource}
        selectedObjects={selectedTables}
        onSelectObjects={setSelectedTables}
        objectPanelType={objectPanelType}
        selectedNodeName={nodeName}
        onOpenObject={handleTableOpen}
        connectionStatus={currentConnectionStatus}
        databaseStatus={databaseStatus}
        mainPanelRef={mainPanelRef}
        connectionId={propActiveConnectionId || storeActiveConnectionId || undefined}
        databaseName={selectedNode.name}
        setSelectedNode={updateSelectedNode}
      />
    );
  }

  // 处理表按钮点击
  const handleTableClick = () => {
    mainPanelRef.current?.createPanel('table', '表', createObjectPanelContent([], selectedNode.type, selectedNode.name))
  }

  // 处理函数按钮点击
  const handleFunctionClick = () => {
    mainPanelRef.current?.createPanel('function', '函数', (
      <FunctionPanel
        dataSource={mockFunctions}
      />
    ))
  }

  // 处理新建查询按钮点击
  const handleNewQueryClick = () => {
    mainPanelRef.current?.createPanel('query', `查询`, (
      <div style={{ padding: '20px' }}>
        <h3>新建查询</h3>
        <p>查询编辑器将在这里显示</p>
      </div>
    ))
  }

  // 处理视图按钮点击
  const handleViewClick = () => {
    mainPanelRef.current?.createPanel('view', '视图', (
      <div style={{ padding: '20px' }}>
        <h3>视图</h3>
        <p>视图列表将在这里显示</p>
      </div>
    ))
  }

  // 处理备份按钮点击
  const handleBackupClick = () => {
    mainPanelRef.current?.createPanel('backup', '备份', (
      <div style={{ padding: '20px' }}>
        <h3>备份</h3>
        <p>备份功能将在这里显示</p>
      </div>
    ))
  }

  // 处理模型按钮点击
  const handleModelClick = () => {
    mainPanelRef.current?.createPanel('model', '模型', (
      <div style={{ padding: '20px' }}>
        <h3>模型</h3>
        <p>模型功能将在这里显示</p>
      </div>
    ))
  }

  // 处理BI按钮点击
  const handleBIClick = () => {
    mainPanelRef.current?.createPanel('bi', 'BI', (
      <div style={{ padding: '20px' }}>
        <h3>BI</h3>
        <p>BI功能将在这里显示</p>
      </div>
    ))
  }

  // 更新当前连接状态
  React.useEffect(() => {
    const activeId = propActiveConnectionId || storeActiveConnectionId
    if (activeId && connectionStates instanceof Map) {
      const status = connectionStates.get(activeId) || ConnectionStatus.DISCONNECTED
      setCurrentConnectionStatus(status)
    } else {
      setCurrentConnectionStatus(ConnectionStatus.DISCONNECTED)
    }
  }, [propActiveConnectionId, storeActiveConnectionId, connectionStates])

  // 处理节点选择事件
  const handleNodeSelect = (node: TreeNode) => {
    // 获取节点的title字符串
    const nodeName = typeof node.title === 'string' ? node.title : undefined;

    // 初始化变量
    let connectionConfig = null;
    let databaseObj = null;
    let tableObj = null;

    // 根据节点类型获取对应的对象
    if (node.type === TreeNodeType.CONNECTION) {
      // 获取连接配置
      connectionConfig = node.data?.metadata?.connection || null;
    } else if (node.type === TreeNodeType.DATABASE) {
      // 获取数据库对象
      databaseObj = databases.get(node.key) || null;
      if (databaseObj?.parentId) {
        // 获取数据库所属的连接
        const connection = databases.get(databaseObj.parentId)?.metadata?.connection || null;
        if (connection) {
          connectionConfig = connection;
        }
      }
    } else if (node.type === TreeNodeType.TABLE) {
      // 获取表对象
      const tableObject = tables.get(node.key);
      if (tableObject) {
        // 构建TableData对象
        tableObj = {
          name: tableObject.name,
          rows: tableObject.metadata?.rows || 0,
          dataLength: typeof tableObject.metadata?.dataLength === 'number' ? formatBytes(tableObject.metadata.dataLength) : '0 KB',
          engine: tableObject.metadata?.engine || '',
          modifyDate: tableObject.metadata?.updateTime || '--',
          collation: tableObject.metadata?.collation || '',
          rowFormat: tableObject.metadata?.rowFormat || '',
          comment: tableObject.metadata?.comment || ''
        };

        // 获取表所属的数据库
        if (tableObject.parentId) {
          databaseObj = databases.get(tableObject.parentId) || null;

          // 获取数据库所属的连接
          if (databaseObj?.parentId) {
            const connection = databases.get(databaseObj.parentId)?.metadata?.connection || null;
            if (connection) {
              connectionConfig = connection;
            }
          }
        }
      }
    }

    // 更新选中节点状态
    updateSelectedNode({ type: node.type, name: nodeName, id: node.key, parentId: node.data?.parentId || undefined }, connectionConfig, databaseObj || undefined, tableObj || undefined);

    // 根据节点类型处理不同的选择事件
    if (node.type === TreeNodeType.TABLE) {
      // 从tables中查找选中的表
      const tableObject = tables.get(node.key)

      if (tableObject) {
        // 构建TableData对象（用于后续处理）
        // 表打开事件由useSelection内部的useEffect自动处理selectedObject更新
        // 设置选中对象
        // 表节点的selectedObject由useSelection内部的useEffect自动处理更新

        // 从tables中获取该表所在数据库的所有表
        const databaseId = tableObject.parentId
        const actualTables = tables instanceof Map
          ? Array.from(tables.values())
            .filter(obj => obj.parentId === databaseId)
            .map(obj => ({
              name: obj.name,
              rows: obj.metadata?.rows || 0,
              dataLength: typeof obj.metadata?.dataLength === 'number' ? formatBytes(obj.metadata.dataLength) : '0 KB',
              engine: obj.metadata?.engine || '',
              modifyDate: obj.metadata?.updateTime || '--',
              collation: obj.metadata?.collation || '',
              rowFormat: obj.metadata?.rowFormat || '',
              comment: obj.metadata?.comment || ''
            }))
          : []

        // 更新默认对象面板的内容
        mainPanelRef.current?.updatePanelContent('object-0', createObjectPanelContent(
          currentConnectionStatus === ConnectionStatus.CONNECTED ? actualTables : [],
          node.type,
          typeof node.title === 'string' ? node.title : undefined,
          databaseId && databaseStates instanceof Map ? databaseStates.get(databaseId) : undefined // 获取表所在数据库的状态
        ))
      }
    } else if (node.type === TreeNodeType.DATABASE) {
      // 从databases中查找选中的数据库
      const databaseObject = databases.get(node.key)

      if (databaseObject) {
        // 数据库节点的selectedObject由useSelection内部的useEffect自动处理更新
      }

      // 双击数据库节点可以加载表并显示表列表
      // 从tables中获取该数据库下的所有表
      const actualTables = tables instanceof Map
        ? Array.from(tables.values())
          .filter(obj => obj.parentId === node.key)
          .map(obj => ({
            name: obj.name,
            rows: obj.metadata?.rows || 0,
            dataLength: typeof obj.metadata?.dataLength === 'number' ? formatBytes(obj.metadata.dataLength) : '0 KB',
            engine: obj.metadata?.engine || '',
            modifyDate: obj.metadata?.updateTime || '--',
            collation: obj.metadata?.collation || '',
            rowFormat: obj.metadata?.rowFormat || '',
            comment: obj.metadata?.comment || ''
          }))
        : []

      // 更新默认对象面板的内容
      mainPanelRef.current?.updatePanelContent('object-0', createObjectPanelContent(
        currentConnectionStatus === ConnectionStatus.CONNECTED ? actualTables : [],
        node.type,
        typeof node.title === 'string' ? node.title : undefined,
        databaseStates instanceof Map ? databaseStates.get(node.key) : undefined
      ))
    } else if (node.type === TreeNodeType.CONNECTION) {
      // 连接节点的selectedObject由useSelection内部的useEffect自动处理更新

      // 处理连接节点点击
      // 更新默认对象面板的内容
      mainPanelRef.current?.updatePanelContent('object-0', (
        <ObjectPanel
          dataSource={[]} // 连接节点选中时显示空表列表
          selectedObjects={selectedTables}
          onSelectObjects={setSelectedTables}
          objectPanelType='table'
          selectedNodeName={typeof node.title === 'string' ? node.title : undefined}
          connectionStatus={currentConnectionStatus}
          onOpenObject={(_record) => {
            // 表打开事件的selectedObject由useSelection内部的useEffect自动处理更新
          }}
          setSelectedNode={updateSelectedNode}
        />
      ))
    } else if (node.type === TreeNodeType.FUNCTION) {
      // 从databases或tables中查找选中的函数（根据实际存储位置）
      const functionObject = tables.get(node.key) || databases.get(node.key)

      if (functionObject) {
        // 函数节点的selectedObject由useSelection内部的useEffect自动处理更新
      }

      // 处理函数节点双击
      mainPanelRef.current?.createPanel('function', '函数', (
        <FunctionPanel
          dataSource={mockFunctions}
        />
      ))
    }
  }



  return (
    <Layout style={{ minHeight: '100vh' }}>
      <HeaderBar
        onConnect={onConnect}
        onNewQuery={handleNewQueryClick}
        onTable={handleTableClick}
        onView={handleViewClick}
        onFunction={handleFunctionClick}
        onUser={onUser}
        onOther={onOther}
        onSearch={onSearch}
        onBackup={handleBackupClick}
        onAutoRun={onAutoRun}
        onModel={handleModelClick}
        onBI={handleBIClick}
      />

      <Layout>
        <Sider width={280} style={{ background: '#fff', borderRight: '1px solid #f0f0f0' }}>
          <ConnectionTree
            onNewConnection={onNewConnection}
            onNodeSelect={handleNodeSelect}
            updateSelectedNode={updateSelectedNode}
          />
        </Sider>

        <Content style={{ margin: '16px', padding: 0, overflowY: 'auto' }}>
          <MainPanel
            ref={mainPanelRef}
            propertiesContent={
              <PropertiesPanel selectedObject={selectedObject} />
            }
          />
        </Content>
      </Layout>
    </Layout>
  )
}

export default AppLayout

// src/components/AppLayout/AppLayout.vue
<template>
  <el-container class="app-layout">
    <el-header style="padding: 0; height: auto;">
      <HeaderBar
        :on-connect="onConnect"
        :on-new-query="handleNewQueryClick"
        :on-table="handleTableClick"
        :on-view="handleViewClick"
        :on-function="handleFunctionClick"
        :on-user="onUser"
        :on-other="onOther"
        :on-search="onSearch"
        :on-backup="handleBackupClick"
        :on-auto-run="onAutoRun"
        :on-model="handleModelClick"
        :on-b-i="handleBIClick"
      />
    </el-header>

    <el-container>
      <el-aside width="280px" class="layout-sider">
        <ConnectionTree
          :on-new-connection="onNewConnection"
          :on-node-select="handleNodeSelect"
          :update-selected-node="updateSelectedNode"
        />
      </el-aside>

      <el-main class="layout-content">
        <MainPanel
          ref="mainPanelRef"
          :properties-content="propertiesContent"
        />
      </el-main>
    </el-container>
  </el-container>
</template>

<script setup lang="ts">
import { ref, computed, watch, h } from 'vue'
import type { VNode } from 'vue'
import HeaderBar from '../HeaderBar/HeaderBar.vue'
import ConnectionTree from '../ConnectionTree/ConnectionTree.vue'
import MainPanel from '../MainPanel/MainPanel.vue'
import ObjectPanel from '../ObjectPanel/ObjectPanel.vue'
import FunctionPanel from '../ObjectPanel/components/ObjectFunctionPanel.vue'
import PropertiesPanel from '../PropertiesPanel/PropertiesPanel.vue'
import type { TreeNode } from '../../types/leftTree/tree'
import type { TreeNodeType } from '../../types/leftTree/tree'
import { useConnectionStore } from '../../stores/connection'
import { ConnectionStatus } from '../../enum/database'
import type { ObjectPanelType } from '../../types/headerBar/headerBar'
import type { TableData } from '../../types/objectPanel'
import type { FunctionData } from '../../types/objectPanel'
import { formatBytes } from '../../utils/formatUtils'
import type { MainPanelRef } from '../MainPanel/MainPanel.vue'

interface AppLayoutProps {
  activeConnectionId?: string | null
  onNewConnection?: () => void
  onConnect?: () => void
  onNewQuery?: () => void
  onTable?: () => void
  onView?: () => void
  onFunction?: () => void
  onUser?: () => void
  onOther?: () => void
  onSearch?: () => void
  onBackup?: () => void
  onAutoRun?: () => void
  onModel?: () => void
  onBI?: () => void
}

const props = withDefaults(defineProps<AppLayoutProps>(), {
  activeConnectionId: null
})

const connectionStore = useConnectionStore()

const mainPanelRef = ref<MainPanelRef | null>(null)

const databases = computed(() => connectionStore.databases)
const tables = computed(() => connectionStore.tables)
const connectionStates = computed(() => connectionStore.connectionStates)
const databaseStates = computed(() => connectionStore.databaseStates)

const selectedTables = ref<TableData[]>([])
const currentConnectionStatus = ref<ConnectionStatus>(ConnectionStatus.DISCONNECTED)
const selectedNode = ref<{ type?: TreeNodeType; name?: string; id?: string; parentId?: string }>({})

const mockFunctions: FunctionData[] = [
  { name: 'get_format', modifyDate: '2023-01-15', functionType: 'FUNCTION', deterministic: true, comment: 'Format a date or time value' },
  { name: 'uuid', modifyDate: '2023-01-15', functionType: 'FUNCTION', deterministic: false, comment: 'Generate a UUID value' },
  { name: 'version', modifyDate: '2023-01-15', functionType: 'FUNCTION', deterministic: false, comment: 'Return version of MySQL server' },
]

const propertiesContent = computed(() => {
  return h('div', { class: 'properties-content' })
})

const setSelectedTables = (records: TableData[]) => {
  selectedTables.value = records
}

const setCurrentConnectionStatus = (status: ConnectionStatus) => {
  currentConnectionStatus.value = status
}

const updateSelectedNode = (
  node: { type?: TreeNodeType; name?: string; id?: string; parentId?: string },
  _connection?: any,
  _database?: any,
  _table?: TableData
) => {
  selectedNode.value = node
}

const createObjectPanelContent = (
  dataSource: TableData[] = [],
  nodeType?: TreeNodeType,
  nodeName?: string,
  databaseStatus?: any
): VNode => {
  let objectPanelType: ObjectPanelType | undefined
  if (nodeType === TreeNodeType.CONNECTION || nodeType === TreeNodeType.DATABASE || nodeType === TreeNodeType.TABLE) {
    objectPanelType = 'table'
  } else if (nodeType === TreeNodeType.VIEW) {
    objectPanelType = 'view'
  } else if (nodeType === TreeNodeType.FUNCTION) {
    objectPanelType = 'function'
  } else if (nodeType === TreeNodeType.USER) {
    objectPanelType = 'user'
  }

  return h(ObjectPanel, {
    dataSource,
    selectedObjects: selectedTables.value,
    onSelectObjects: setSelectedTables,
    objectPanelType,
    selectedNodeName: nodeName,
    connectionStatus: currentConnectionStatus.value,
    databaseStatus,
    mainPanelRef: mainPanelRef.value,
    connectionId: props.activeConnectionId || undefined,
    databaseName: selectedNode.value.name,
    setSelectedNode: updateSelectedNode
  })
}

const handleTableClick = () => {
  if (mainPanelRef.value) {
    mainPanelRef.value.createPanel('table', '表', createObjectPanelContent([], selectedNode.value.type, selectedNode.value.name))
  }
}

const handleFunctionClick = () => {
  if (mainPanelRef.value) {
    mainPanelRef.value.createPanel('function', '函数', h(FunctionPanel, { dataSource: mockFunctions }))
  }
}

const handleNewQueryClick = () => {
  if (mainPanelRef.value) {
    mainPanelRef.value.createPanel('query', '查询', h('div', { style: { padding: '20px' } }, [
      h('h3', {}, '新建查询'),
      h('p', {}, '查询编辑器将在这里显示')
    ]))
  }
}

const handleViewClick = () => {
  if (mainPanelRef.value) {
    mainPanelRef.value.createPanel('view', '视图', h('div', { style: { padding: '20px' } }, [
      h('h3', {}, '视图'),
      h('p', {}, '视图列表将在这里显示')
    ]))
  }
}

const handleBackupClick = () => {
  if (mainPanelRef.value) {
    mainPanelRef.value.createPanel('backup', '备份', h('div', { style: { padding: '20px' } }, [
      h('h3', {}, '备份'),
      h('p', {}, '备份功能将在这里显示')
    ]))
  }
}

const handleModelClick = () => {
  if (mainPanelRef.value) {
    mainPanelRef.value.createPanel('model', '模型', h('div', { style: { padding: '20px' } }, [
      h('h3', {}, '模型'),
      h('p', {}, '模型功能将在这里显示')
    ]))
  }
}

const handleBIClick = () => {
  if (mainPanelRef.value) {
    mainPanelRef.value.createPanel('bi', 'BI', h('div', { style: { padding: '20px' } }, [
      h('h3', {}, 'BI'),
      h('p', {}, 'BI功能将在这里显示')
    ]))
  }
}

const handleNodeSelect = (node: TreeNode) => {
  const nodeName = typeof node.title === 'string' ? node.title : undefined

  let connectionConfig = null
  let databaseObj = null
  let tableObj = null

  if (node.type === TreeNodeType.CONNECTION) {
    connectionConfig = node.data?.metadata?.connection || null
  } else if (node.type === TreeNodeType.DATABASE) {
    databaseObj = databases.value.get(node.key) || null
    if (databaseObj?.parentId) {
      const connection = databases.value.get(databaseObj.parentId)?.metadata?.connection || null
      if (connection) {
        connectionConfig = connection
      }
    }
  } else if (node.type === TreeNodeType.TABLE) {
    const tableObject = tables.value.get(node.key)
    if (tableObject) {
      tableObj = {
        name: tableObject.name,
        rows: tableObject.metadata?.rows || 0,
        dataLength: typeof tableObject.metadata?.dataLength === 'number' ? formatBytes(tableObject.metadata.dataLength) : '0 KB',
        engine: tableObject.metadata?.engine || '',
        modifyDate: tableObject.metadata?.updateTime || '--',
        collation: tableObject.metadata?.collation || '',
        rowFormat: tableObject.metadata?.rowFormat || '',
        comment: tableObject.metadata?.comment || ''
      }

      if (tableObject.parentId) {
        databaseObj = databases.value.get(tableObject.parentId) || null
        if (databaseObj?.parentId) {
          const connection = databases.value.get(databaseObj.parentId)?.metadata?.connection || null
          if (connection) {
            connectionConfig = connection
          }
        }
      }
    }
  }

  updateSelectedNode(
    { type: node.type, name: nodeName, id: node.key, parentId: node.data?.parentId || undefined },
    connectionConfig,
    databaseObj || undefined,
    tableObj || undefined
  )

  if (node.type === TreeNodeType.TABLE) {
    const tableObject = tables.value.get(node.key)
    if (tableObject) {
      const databaseId = tableObject.parentId
      const actualTables = Array.from(tables.value.values())
        .filter(obj => obj.parentId === databaseId)
        .map(obj => ({
          name: obj.name,
          rows: obj.metadata?.rows || 0,
          dataLength: typeof obj.metadata?.dataLength === 'number' ? formatBytes(obj.metadata.dataLength) : '0 KB',
          engine: obj.metadata?.engine || '',
          modifyDate: obj.metadata?.updateTime || '--',
          collation: obj.metadata?.collation || '',
          rowFormat: obj.metadata?.rowFormat || '',
          comment: obj.metadata?.comment || ''
        }))

      if (mainPanelRef.value) {
        mainPanelRef.value.updatePanelContent('object-0', createObjectPanelContent(
          currentConnectionStatus.value === ConnectionStatus.CONNECTED ? actualTables : [],
          node.type,
          nodeName,
          databaseId ? databaseStates.value.get(databaseId) : undefined
        ))
      }
    }
  } else if (node.type === TreeNodeType.DATABASE) {
    const actualTables = Array.from(tables.value.values())
      .filter(obj => obj.parentId === node.key)
      .map(obj => ({
        name: obj.name,
        rows: obj.metadata?.rows || 0,
        dataLength: typeof obj.metadata?.dataLength === 'number' ? formatBytes(obj.metadata.dataLength) : '0 KB',
        engine: obj.metadata?.engine || '',
        modifyDate: obj.metadata?.updateTime || '--',
        collation: obj.metadata?.collation || '',
        rowFormat: obj.metadata?.rowFormat || '',
        comment: obj.metadata?.comment || ''
      }))

    if (mainPanelRef.value) {
      mainPanelRef.value.updatePanelContent('object-0', createObjectPanelContent(
        currentConnectionStatus.value === ConnectionStatus.CONNECTED ? actualTables : [],
        node.type,
        nodeName,
        databaseStates.value.get(node.key)
      ))
    }
  } else if (node.type === TreeNodeType.CONNECTION) {
    if (mainPanelRef.value) {
      mainPanelRef.value.updatePanelContent('object-0', h(ObjectPanel, {
        dataSource: [],
        selectedObjects: selectedTables.value,
        onSelectObjects: setSelectedTables,
        objectPanelType: 'table',
        selectedNodeName: nodeName,
        connectionStatus: currentConnectionStatus.value,
        setSelectedNode: updateSelectedNode
      }))
    }
  } else if (node.type === TreeNodeType.FUNCTION) {
    if (mainPanelRef.value) {
      mainPanelRef.value.createPanel('function', '函数', h(FunctionPanel, { dataSource: mockFunctions }))
    }
  }
}

watch(
  () => [props.activeConnectionId, connectionStates.value],
  () => {
    const activeId = props.activeConnectionId
    if (activeId && connectionStates.value instanceof Map) {
      const status = connectionStates.value.get(activeId) || ConnectionStatus.DISCONNECTED
      setCurrentConnectionStatus(status)
    } else {
      setCurrentConnectionStatus(ConnectionStatus.DISCONNECTED)
    }
  },
  { immediate: true }
)
</script>

<style scoped>
.app-layout {
  min-height: 100vh;
}

.layout-sider {
  background: #fff;
  border-right: 1px solid #f0f0f0;
}

.layout-content {
  margin: 16px;
  padding: 0;
  overflow-y: auto;
}
</style>
