// src/clientComponents/ConnectionDialog/index.vue
<template>
  <el-dialog
    :title="connection ? '编辑数据库连接' : '新建数据库连接'"
    v-model="dialogVisible"
    width="600px"
    destroy-on-close
    :close-on-click-modal="false"
  >
    <el-form
      ref="formRef"
      :model="formData"
      :rules="formRules"
      label-width="100px"
      label-position="left"
    >
      <el-tabs v-model="activeTab">
        <el-tab-pane label="基本配置" name="basic">
          <el-form-item label="连接名称" prop="name">
            <el-input v-model="formData.name" placeholder="例如: 本地MySQL" />
          </el-form-item>

          <el-form-item label="数据库类型" prop="type">
            <el-select v-model="formData.type" @change="handleTypeChange" style="width: 100%">
              <el-option label="MySQL" :value="ConnectionType.MySQL" />
              <el-option label="PostgreSQL" :value="ConnectionType.PostgreSQL" />
              <el-option label="MongoDB" :value="ConnectionType.MongoDB" />
              <el-option label="Redis" :value="ConnectionType.Redis" />
              <el-option label="SQL Server" :value="ConnectionType.SQLServer" />
              <el-option label="SQLite" :value="ConnectionType.SQLite" />
            </el-select>
          </el-form-item>

          <el-row :gutter="16">
            <el-col :span="12">
              <el-form-item label="主机名" prop="host">
                <el-input v-model="formData.host" placeholder="localhost" />
              </el-form-item>
            </el-col>
            <el-col :span="12">
              <el-form-item label="端口" prop="port">
                <el-input-number v-model="formData.port" :min="1" :max="65535" style="width: 100%" />
              </el-form-item>
            </el-col>
          </el-row>

          <el-row :gutter="16">
            <el-col :span="12">
              <el-form-item label="用户名" prop="username">
                <el-input v-model="formData.username" placeholder="root" />
              </el-form-item>
            </el-col>
            <el-col :span="12">
              <el-form-item label="密码">
                <el-input v-model="formData.password" type="password" placeholder="" show-password />
              </el-form-item>
            </el-col>
          </el-row>

          <el-form-item label="数据库名">
            <el-input v-model="formData.database" placeholder="默认数据库" />
          </el-form-item>
        </el-tab-pane>

        <el-tab-pane label="高级配置" name="advanced">
          <el-card header="SSL配置" shadow="never" style="margin-bottom: 16px">
            <el-form-item label="启用SSL">
              <el-switch v-model="formData.ssl" />
            </el-form-item>
          </el-card>

          <el-card header="SSH隧道" shadow="never" style="margin-bottom: 16px">
            <el-form-item label="启用SSH隧道">
              <el-switch v-model="formData.ssh" />
            </el-form-item>

            <el-row :gutter="16">
              <el-col :span="12">
                <el-form-item label="SSH主机名">
                  <el-input v-model="formData.sshHost" placeholder="SSH服务器地址" />
                </el-form-item>
              </el-col>
              <el-col :span="12">
                <el-form-item label="SSH端口">
                  <el-input-number v-model="formData.sshPort" :min="1" :max="65535" :step="1" style="width: 100%" />
                </el-form-item>
              </el-col>
            </el-row>

            <el-row :gutter="16">
              <el-col :span="12">
                <el-form-item label="SSH用户名">
                  <el-input v-model="formData.sshUsername" placeholder="SSH用户名" />
                </el-form-item>
              </el-col>
              <el-col :span="12">
                <el-form-item label="SSH密码">
                  <el-input v-model="formData.sshPassword" type="password" placeholder="SSH密码" show-password />
                </el-form-item>
              </el-col>
            </el-row>

            <el-form-item label="SSH私钥">
              <el-input v-model="formData.sshPrivateKey" type="textarea" :rows="4" placeholder="SSH私钥内容" />
            </el-form-item>

            <el-form-item label="SSH私钥密码">
              <el-input v-model="formData.sshPassphrase" type="password" placeholder="SSH私钥密码" show-password />
            </el-form-item>
          </el-card>

          <el-card header="连接选项" shadow="never">
            <el-row :gutter="16">
              <el-col :span="12">
                <el-form-item label="连接超时(秒)">
                  <el-input-number v-model="formData.timeout" :min="1" :max="300" style="width: 100%" />
                </el-form-item>
              </el-col>
              <el-col :span="12">
                <el-form-item label="字符集">
                  <el-input v-model="formData.charset" placeholder="例如: utf8mb4" />
                </el-form-item>
              </el-col>
            </el-row>

            <el-form-item label="最大连接数">
              <el-input-number v-model="formData.maxConnections" :min="1" :max="100" style="width: 100%" />
            </el-form-item>
          </el-card>
        </el-tab-pane>
      </el-tabs>
    </el-form>

    <template #footer>
      <el-space :size="16">
        <el-button @click="handleTestConnection" :loading="testLoading">测试连接</el-button>
        <el-button @click="handleCancel">取消</el-button>
        <el-button type="primary" @click="handleSave" :loading="loading">
          {{ connection ? '更新' : '保存' }}
        </el-button>
      </el-space>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, reactive, watch, computed } from 'vue'
import { type FormInstance, type FormRules } from 'element-plus'
import { useConnectionStore } from '../../stores/connection'
import { ConnectionType, ConnectionConfig, TreeNode } from '../../../electron/model/database'

interface ConnectionDialogProps {
  visible: boolean
  connection?: TreeNode | null
}

const props = withDefaults(defineProps<ConnectionDialogProps>(), {
  visible: false,
  connection: null
})

const emit = defineEmits<{
  (e: 'update:visible', value: boolean): void
  (e: 'cancel'): void
}>()

const connectionStore = useConnectionStore()

const formRef = ref<FormInstance | null>(null)
const activeTab = ref('basic')
const loading = ref(false)
const testLoading = ref(false)

const defaultPorts: Record<ConnectionType, number> = {
  [ConnectionType.MySQL]: 3306,
  [ConnectionType.PostgreSQL]: 5432,
  [ConnectionType.MongoDB]: 27017,
  [ConnectionType.Redis]: 6379,
  [ConnectionType.SQLServer]: 1433,
  [ConnectionType.SQLite]: 0
}

const formData = reactive({
  name: '',
  type: ConnectionType.MySQL as ConnectionType,
  host: '127.0.0.1',
  port: defaultPorts[ConnectionType.MySQL],
  username: 'root',
  password: '123456',
  database: '',
  ssl: false,
  ssh: false,
  sshHost: '',
  sshPort: 22,
  sshUsername: '',
  sshPassword: '',
  sshPrivateKey: '',
  sshPassphrase: '',
  timeout: 30,
  charset: 'utf8mb4',
  maxConnections: 10
})

const formRules: FormRules = {
  name: [{ required: true, message: '请输入连接名称', trigger: 'blur' }],
  type: [{ required: true, message: '请选择数据库类型', trigger: 'change' }],
  host: [{ required: true, message: '请输入主机名', trigger: 'blur' }],
  port: [{ required: true, message: '请输入端口号', trigger: 'blur' }],
  username: [{ required: true, message: '请输入用户名', trigger: 'blur' }]
}

const dialogVisible = computed({
  get: () => {
    console.log('ConnectionDialog dialogVisible get:', props.visible)
    return props.visible
  },
  set: (value) => {
    console.log('ConnectionDialog dialogVisible set:', value)
    emit('update:visible', value)
  }
})

watch(() => props.visible, (visible) => {
  console.log('ConnectionDialog watch visible:', visible, 'connection:', props.connection)
  if (visible && props.connection) {
    try {
      const decryptedConnection = connectionStore.decryptConnection(props.connection)
      Object.assign(formData, {
        ...decryptedConnection,
        type: decryptedConnection.type,
        port: decryptedConnection.port || defaultPorts[decryptedConnection.type]
      })
    } catch (error) {
      console.error('Error decrypting connection:', error)
    }
  } else if (visible) {
    Object.assign(formData, {
      name: '',
      type: ConnectionType.MySQL,
      host: '127.0.0.1',
      port: defaultPorts[ConnectionType.MySQL],
      username: 'root',
      password: '123456',
      database: '',
      ssl: false,
      ssh: false,
      sshHost: '',
      sshPort: 22,
      sshUsername: '',
      sshPassword: '',
      sshPrivateKey: '',
      sshPassphrase: '',
      timeout: 30,
      charset: 'utf8mb4',
      maxConnections: 10
    })
  }
})

const handleTypeChange = (type: ConnectionType) => {
  formData.port = defaultPorts[type]
}

const handleTestConnection = async () => {
  if (!formRef.value) return

  try {
    await formRef.value.validate()
    testLoading.value = true

    const conectionNode:TreeNode ={
      ...props.connection,
      connectionConfig: {
        ...formData,
        type: formData.type,
        id: 'test-connection',
        password: formData.password || ''
      }
    }

    const result = await connectionStore.testConnection(conectionNode)
    if (result.success) {
      CTMessage.success('连接测试成功！')
    } else {
      CTMessage.error(`连接测试失败：${result.error || '未知错误'}`)
    }
  } catch (error: any) {
    CTMessage.error(`表单验证失败：${error?.message || '请检查输入'}`)
  } finally {
    testLoading.value = false
  }
}

const handleSave = async () => {
  if (!formRef.value) return

  try {
    await formRef.value.validate()
    loading.value = true

    if (props.connection) {
      connectionStore.updateConnection(props.connection.id, { ...formData })
      CTMessage.success('连接更新成功！')
    } else {
      connectionStore.addConnection({ ...formData })
      CTMessage.success('连接添加成功！')
    }

    handleCancel()
  } catch (error: any) {
    CTMessage.error(`保存失败：${error?.message || '请检查输入'}`)
  } finally {
    loading.value = false
  }
}

const handleCancel = () => {
  emit('cancel')
}
</script>

// src/components/ConnectionDialog.tsx
import React, { useState, useEffect } from 'react'
import { Modal, Form, Input, Select, Switch, InputNumber, Button, message, Space, Card, Tabs } from 'antd'
import { DatabaseOutlined, CheckCircleOutlined, SaveOutlined, CloseOutlined } from '@ant-design/icons'
import { ConnectionConfig, DatabaseType } from '../types/connection'
import { useConnectionStore } from '../store/connectionStore'

interface ConnectionDialogProps {
  visible: boolean
  onCancel: () => void
  connection?: ConnectionConfig | null
}

const { Option } = Select
const { TabPane } = Tabs

const ConnectionDialog: React.FC<ConnectionDialogProps> = ({ visible, onCancel, connection }) => {
  const [form] = Form.useForm<Omit<ConnectionConfig, 'id'>>()
  const [loading, setLoading] = useState(false)
  const [testLoading, setTestLoading] = useState(false)
  const [activeTab, setActiveTab] = useState('basic')
  
  const addConnection = useConnectionStore((state) => state.addConnection)
  const updateConnection = useConnectionStore((state) => state.updateConnection)
  const testConnection = useConnectionStore((state) => state.testConnection)

  // 数据库默认端口映射
  const defaultPorts: Record<DatabaseType, number> = {
    [DatabaseType.MYSQL]: 3306,
    [DatabaseType.POSTGRESQL]: 5432,
    [DatabaseType.MONGODB]: 27017,
    [DatabaseType.REDIS]: 6379,
    [DatabaseType.SQLSERVER]: 1433,
    [DatabaseType.SQLITE]: 0
  }

  // 当连接变化时更新表单
  useEffect(() => {
    if (connection) {
      form.setFieldsValue({
        ...connection,
        type: connection.type,
        port: connection.port || defaultPorts[connection.type]
      })
    } else {
      form.resetFields()
      form.setFieldsValue({ host: '127.0.0.1', username: 'root', password: '123456', type: DatabaseType.MYSQL, port: defaultPorts[DatabaseType.MYSQL] })
    }
  }, [connection, form])

  // 处理数据库类型变化，更新默认端口
  const handleTypeChange = (type: DatabaseType) => {
    form.setFieldsValue({ port: defaultPorts[type] })
  }

  // 测试连接
  const handleTestConnection = async () => {
    try {
      setTestLoading(true)
      const values = await form.validateFields()
      const testConfig: ConnectionConfig = {
        ...values,
        id: 'test-connection',
        password: values.password || ''
      }
      
      const success = await testConnection(testConfig)
      if (success) {
        message.success('连接测试成功！')
      } else {
        message.error('连接测试失败，请检查配置')
      }
    } catch (error) {
      message.error('表单验证失败，请检查输入')
    } finally {
      setTestLoading(false)
    }
  }

  // 保存连接
  const handleSave = async () => {
    try {
      setLoading(true)
      const values = await form.validateFields()
      
      if (connection) {
        // 更新现有连接
        updateConnection(connection.id, values)
        message.success('连接更新成功！')
      } else {
        // 添加新连接
        addConnection(values)
        message.success('连接添加成功！')
      }
      
      onCancel()
    } catch (error) {
      message.error('保存失败，请检查输入')
    } finally {
      setLoading(false)
    }
  }



  return (
    <Modal
      title={connection ? '编辑数据库连接' : '新建数据库连接'}
      visible={visible}
      onCancel={onCancel}
      footer={null}
      width={600}
      destroyOnClose
    >
      <Form
        form={form}
        layout="horizontal"
        initialValues={{ type: DatabaseType.MYSQL, port: defaultPorts[DatabaseType.MYSQL] }}
        labelCol={{ span: 6 }}
        wrapperCol={{ span: 18 }}
      >
        <Tabs activeKey={activeTab} onChange={setActiveTab}>
          <TabPane tab="基本配置" key="basic">
            <Form.Item name="name" label="连接名称" rules={[{ required: true, message: '请输入连接名称' }]}>
              <Input placeholder="例如: 本地MySQL" />
            </Form.Item>
            
            <Form.Item name="type" label="数据库类型" rules={[{ required: true, message: '请选择数据库类型' }]}>
              <Select onChange={handleTypeChange}>
                <Option value={DatabaseType.MYSQL}>
                  <Space>
                    <DatabaseOutlined />
                    MySQL
                  </Space>
                </Option>
                <Option value={DatabaseType.POSTGRESQL}>
                  <Space>
                    <DatabaseOutlined />
                    PostgreSQL
                  </Space>
                </Option>
                <Option value={DatabaseType.MONGODB}>
                  <Space>
                    <DatabaseOutlined />
                    MongoDB
                  </Space>
                </Option>
                <Option value={DatabaseType.REDIS}>
                  <Space>
                    <DatabaseOutlined />
                    Redis
                  </Space>
                </Option>
                <Option value={DatabaseType.SQLSERVER}>
                  <Space>
                    <DatabaseOutlined />
                    SQL Server
                  </Space>
                </Option>
                <Option value={DatabaseType.SQLITE}>
                  <Space>
                    <DatabaseOutlined />
                    SQLite
                  </Space>
                </Option>
              </Select>
            </Form.Item>

            {/* 主机和端口在同一行 */}
            <div style={{ display: 'flex', gap: '16px', marginBottom: '16px' }}>
              <Form.Item 
                name="host" 
                label="主机名" 
                rules={[{ required: true, message: '请输入主机名' }]}
                style={{ flex: 1, marginBottom: 0 }}
                labelCol={{ span: 6 }}
                wrapperCol={{ span: 18 }}
              >
                <Input placeholder="localhost" />
              </Form.Item>
              <Form.Item 
                name="port" 
                label="端口" 
                rules={[{ required: true, message: '请输入端口号' }]}
                style={{ flex: 1, marginBottom: 0 }}
                labelCol={{ span: 6 }}
                wrapperCol={{ span: 18 }}
              >
                <InputNumber min={1} max={65535} style={{ width: '100%' }} />
              </Form.Item>
            </div>

            {/* 用户名和密码在同一行 */}
            <div style={{ display: 'flex', gap: '16px', marginBottom: '16px' }}>
              <Form.Item 
                name="username" 
                label="用户名" 
                rules={[{ required: true, message: '请输入用户名' }]}
                style={{ flex: 1, marginBottom: 0 }}
                labelCol={{ span: 6 }}
                wrapperCol={{ span: 18 }}
              >
                <Input placeholder="root" />
              </Form.Item>
              <Form.Item 
                name="password" 
                label="密码"
                style={{ flex: 1, marginBottom: 0 }}
                labelCol={{ span: 6 }}
                wrapperCol={{ span: 18 }}
              >
                <Input.Password placeholder="" />
              </Form.Item>
            </div>

            {/* 数据库名 */}
            <Form.Item name="database" label="数据库名">
              <Input placeholder="默认数据库" />
            </Form.Item>
          </TabPane>
          
          <TabPane tab="高级配置" key="advanced">
            <Card type="inner" title="SSL配置" style={{ marginBottom: 16 }}>
              <Form.Item name="ssl" label="启用SSL">
                <Switch />
              </Form.Item>
            </Card>
            
            <Card type="inner" title="SSH隧道" style={{ marginBottom: 16 }}>
              <Form.Item name="ssh" label="启用SSH隧道">
                <Switch />
              </Form.Item>
              
              <div style={{ display: 'flex', gap: '16px', marginBottom: '16px' }}>
                <Form.Item 
                  name="sshHost" 
                  label="SSH主机名"
                  style={{ flex: 1, marginBottom: 0 }}
                  labelCol={{ span: 6 }}
                  wrapperCol={{ span: 18 }}
                >
                  <Input placeholder="SSH服务器地址" />
                </Form.Item>
                <Form.Item 
                  name="sshPort" 
                  label="SSH端口"
                  style={{ flex: 1, marginBottom: 0 }}
                  labelCol={{ span: 6 }}
                  wrapperCol={{ span: 18 }}
                >
                  <InputNumber min={1} max={65535} defaultValue={22} style={{ width: '100%' }} />
                </Form.Item>
              </div>
              
              <div style={{ display: 'flex', gap: '16px', marginBottom: '16px' }}>
                <Form.Item 
                  name="sshUsername" 
                  label="SSH用户名"
                  style={{ flex: 1, marginBottom: 0 }}
                  labelCol={{ span: 6 }}
                  wrapperCol={{ span: 18 }}
                >
                  <Input placeholder="SSH用户名" />
                </Form.Item>
                <Form.Item 
                  name="sshPassword" 
                  label="SSH密码"
                  style={{ flex: 1, marginBottom: 0 }}
                  labelCol={{ span: 6 }}
                  wrapperCol={{ span: 18 }}
                >
                  <Input.Password placeholder="SSH密码" />
                </Form.Item>
              </div>
              
              <Form.Item name="sshPrivateKey" label="SSH私钥">
                <Input.TextArea rows={4} placeholder="SSH私钥内容" />
              </Form.Item>
              
              <Form.Item name="sshPassphrase" label="SSH私钥密码">
                <Input.Password placeholder="SSH私钥密码" />
              </Form.Item>
            </Card>
            
            <Card type="inner" title="连接选项">
              <div style={{ display: 'flex', gap: '16px', marginBottom: '16px' }}>
                <Form.Item 
                  name="timeout" 
                  label="连接超时(秒)"
                  style={{ flex: 1, marginBottom: 0 }}
                  labelCol={{ span: 6 }}
                  wrapperCol={{ span: 18 }}
                >
                  <InputNumber min={1} max={300} style={{ width: '100%' }} />
                </Form.Item>
                <Form.Item 
                  name="charset" 
                  label="字符集"
                  style={{ flex: 1, marginBottom: 0 }}
                  labelCol={{ span: 6 }}
                  wrapperCol={{ span: 18 }}
                >
                  <Input placeholder="例如: utf8mb4" />
                </Form.Item>
              </div>
              
              <Form.Item name="maxConnections" label="最大连接数">
                <InputNumber min={1} max={100} style={{ width: '100%' }} />
              </Form.Item>
            </Card>
          </TabPane>
        </Tabs>
        
        <Space style={{ width: '100%', justifyContent: 'flex-end', marginTop: 24 }}>
          <Button
            icon={<CheckCircleOutlined />}
            onClick={handleTestConnection}
            loading={testLoading}
          >
            测试连接
          </Button>
          <Button
            icon={<CloseOutlined />}
            onClick={onCancel}
          >
            取消
          </Button>
          <Button
            type="primary"
            icon={<SaveOutlined />}
            onClick={handleSave}
            loading={loading}
          >
            {connection ? '更新' : '保存'}
          </Button>
        </Space>
      </Form>
    </Modal>
  )
}

export default ConnectionDialog
