// src/App.tsx
import React, { useState } from 'react'
import './App.css'
import ConnectionDialog from './components/ConnectionDialog'
import QueryEditor from './components/QueryEditor'
import AppLayout from './components/AppLayout'
import { useConnectionStore } from './store/connectionStore'
import { ConnectionConfig } from './types/connection'
import { useIpcCommunication } from './hooks/useIpcCommunication'

const App = () => {
  const [connectionDialogVisible, setConnectionDialogVisible] = useState(false)
  const [editingConnection, setEditingConnection] = useState<ConnectionConfig | null>(null)
  const activeConnectionId = useConnectionStore((state) => state.activeConnectionId)
  const handleNewConnection = () => {
    setEditingConnection(null)
    setConnectionDialogVisible(true)
  }

  useIpcCommunication(handleNewConnection)

  return (
    <div>
      <AppLayout
        activeConnectionId={activeConnectionId}
        onNewConnection={handleNewConnection}
      >
        {activeConnectionId ? (
          <QueryEditor />
        ) : null}
      </AppLayout>

      <ConnectionDialog
        visible={connectionDialogVisible}
        onCancel={() => {
          setConnectionDialogVisible(false)
          setEditingConnection(null)
        }}
        connection={editingConnection}
      />
    </div>
  )
}

export default App

// src/App.vue
<template>
  <AppLayout
    :active-connection-id="activeConnectionId"
    @new-connection="handleNewConnection"
    @edit-connection="handleEditConnection"
  >
    <QueryEditor v-if="activeConnectionId" />
  </AppLayout>

  <ConnectionDialog
    v-model:visible="connectionDialogVisible"
    :connection="editingConnection"
    @cancel="handleCancelDialog"
  />
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import AppLayout from './components/AppLayout/AppLayout.vue'
import QueryEditor from './components/QueryEditor.vue'
import ConnectionDialog from './components/ConnectionDialog.vue'
import { useConnectionStore } from './stores/connection'
import type { ConnectionConfig } from './types/leftTree/connection'
import { useIpcCommunication } from './composables/useIpcCommunication'

const connectionDialogVisible = ref(false)
const editingConnection = ref<ConnectionConfig | null>(null)

const connectionStore = useConnectionStore()
const activeConnectionId = computed(() => connectionStore.activeConnectionId)

const handleNewConnection = () => {
  editingConnection.value = null
  connectionDialogVisible.value = true
}

const handleEditConnection = (connection: ConnectionConfig) => {
  const decryptedConnection = connectionStore.decryptConnection(connection)
  editingConnection.value = decryptedConnection
  connectionDialogVisible.value = true
}

const handleCancelDialog = () => {
  connectionDialogVisible.value = false
  editingConnection.value = null
}

useIpcCommunication(handleNewConnection)
</script>

<style>
#app {
  width: 100%;
  height: 100vh;
}
</style>
